@endpoint = https://lfvjoiwqvgvcvljfyngk.supabase.co/rest/v1/Orders
@apiKey = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmdmpvaXdxdmd2Y3ZsamZ5bmdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4Mzk5MjMsImV4cCI6MjA3OTQxNTkyM30.eaPFsTY7GtBB0i3tqlNKP8u_atngnKsL_PyfY7e5BVw

### GET
GET {{ endpoint }}
apikey: {{ apiKey }}
Authorization: Bearer {{ apiKey }}

### POST
POST {{ endpoint }}
apikey: {{ apiKey }}
Authorization: Bearer {{ apiKey }}
Content-Type: application/json

{
    "title": "Projeto Etapa I",
    "due": "2025-11-15",
    "level": "high",
    "description": "Projeto prioritário de angular!",
    "status": "todo"
}

### PATCH
PATCH {{ endpoint }}?id=eq.24
apikey: {{ apiKey }}
Authorization: Bearer {{ apiKey }}
Content-Type: application/json

{
    "status": "todo"
}

### DELETE
DELETE {{ endpoint }}?id=eq.9
apikey: {{ apiKey }}
Authorization: Bearer {{ apiKey }}

https://veoumsjwfxjadzaosiqf.supabase.co/rest/v1/tasks?id=eq.8
https://veoumsjwfxjadzaosiqf.supabase.co/rest/v1/tasks?id=eq.8