@endpoint = https://lfvjoiwqvgvcvljfyngk.supabase.co/rest/v1/Orders
@apiKey = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmdmpvaXdxdmd2Y3ZsamZ5bmdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4Mzk5MjMsImV4cCI6MjA3OTQxNTkyM30.eaPFsTY7GtBB0i3tqlNKP8u_atngnKsL_PyfY7e5BVw

### GET
GET {{ endpoint }}
apikey: {{ apiKey }}
Authorization: Bearer {{ apiKey }}

### GET
GET {{ endpoint }}?numero=eq.3
apikey: {{ apiKey }}
Authorization: Bearer {{ apiKey }}


### POST
POST {{ endpoint }}
apikey: {{ apiKey }}
Authorization: Bearer {{ apiKey }}
Content-Type: application/json

{
    "numero": 3,
    "products": [{
        "id":1,
        "quantity":3 
        }]
}

### PATCH
PATCH {{ endpoint }}?numero=eq.3
apikey: {{ apiKey }}
Authorization: Bearer {{ apiKey }}
Content-Type: application/json

{
    "aberta": "FALSE"
}

### DELETE
DELETE {{ endpoint }}?numero=eq.1
apikey: {{ apiKey }}
Authorization: Bearer {{ apiKey }}

https://veoumsjwfxjadzaosiqf.supabase.co/rest/v1/tasks?id=eq.8
https://veoumsjwfxjadzaosiqf.supabase.co/rest/v1/tasks?id=eq.8