@endpoint = http://localhost:8080/dashboard
@apiKey = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmdmpvaXdxdmd2Y3ZsamZ5bmdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4Mzk5MjMsImV4cCI6MjA3OTQxNTkyM30.eaPFsTY7GtBB0i3tqlNKP8u_atngnKsL_PyfY7e5BVw

### GET
GET https://noncognizant-dorthey-unprepossessingly.ngrok-free.dev/dashboard/all


### GET by id
GET http://localhost:8080/dashboard/89



### POST
POST {{ endpoint }}
Content-Type: application/json

{
  "numero": 89,
  "produtos": [
    { "id": 1, "quantity": 1 },
    { "id": 3, "quantity": 2 }
  ]
}

### PATCH
PATCH http://localhost:8080/dashboard/31
Content-Type: application/json

{
  "aberta": "FALSE"
}

### PUT
PUT http://localhost:8080/dashboard/34
Content-Type: application/json

{
  "numero": 20,
  "produtos": []
}

### DELETE
DELETE {{ endpoint }}?numero=eq.1
apikey: {{ apiKey }}
Authorization: Bearer {{ apiKey }}

https://veoumsjwfxjadzaosiqf.supabase.co/rest/v1/tasks?id=eq.8
https://veoumsjwfxjadzaosiqf.supabase.co/rest/v1/tasks?id=eq.8